---
title: "Практическая работа 4. Генерация распределений. Проверка определений известных распределений"
author: "Юрченков Иван Александрович, ассистент кафедры ПМ"
date: "`r Sys.Date()`"
mainfont: SourceSansPro
output:
  pdf_document: 
    latex_engine: lualatex
    keep_tex: yes
    highlight: haddock
    fig_width: 8
    fig_height: 7
    fig_caption: yes
---

```{r, echo=FALSE, results='hide', error=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, dev="cairo_pdf", dpi = 500, out.width="70%", fig.align='center')
library(dplyr)
library(stringr)
```

# **Постановка задачи**

1. **Сгенерировать выборку нормального распределения $\ Y\sim N(\mu, \sigma^2)\ $ используя определение центральной предельной теоремы**. 

- На основе $\ n \approx 10\div 20\ $ равномерно распределенных случайных реализаций случайных величин образовать новую выборку по определению центральной предельной теоремы. 

Если $\ Y_{i} \sim U(a_i, b_i), \ i = 1, 2, \dots, n\ $, где $\ Y_{i}\ -$ равномерно распределенная реализация случайной величины со случайными параметрами $\ a_i \in \mathbb{R},\ b_i \in \mathbb{R}\ $, то ожидаемая нормально распределенная величина $\ Y\ $ будет найдена как:

$$
Y = \sum_{i=1}^{n} Y_i, \ i=1,2,\dots, n
$$

- Для получившейся выборки построить гистограмму, визуализировать на гистограмме теоретическую плотность нормального распределения по несмещенным точечным оценкам $\ \hat{\mu}, \hat{\sigma}\ $.

- Провести тест на нормальное распределение с помощью критерия $\ \chi^2$-Пирсона. Степени свободы рассчитывать как $\ k = n - 1\ $.

Для генерации выборок рекомендуется пользоваться встроенными в компьютерные статистические пакеты функциями генерации **равномерно распределённых случайных величин**, которые задаются с помощью параметров границ интервала генерации чисел $a$ и $b$.

2. **Сгенерировать выборку $\ \chi^2$-распределения $\ R \sim \chi_{k}^2\ $ используя определение распределения $\ \chi^2\ $**. 

- На основе $\ Z$-оценок нормально распределенных случайных реализаций случайных величин $\ L_{i} \sim N(\mu_i, \sigma_i^2)\ $ образовать новую выборку по определению $\ \chi^2$-распределения:

$$
R = \sum_{i = 1}^{n} Z[L_i]^2,\ \ Z[L_i] = \frac{L - E[L]}{\sigma[L]}, \ L_i \sim N(\mu_i, \sigma_i^2),\ i = 1,2,\dots,n
$$

- Для получившейся выборки построить гистограмму, визуализировать на гистограмме теоретическую плотность $\ \chi_k^2\ $ распределения c $\ k = n-1\ $ степенями свободы.

- Провести тест на $\ \chi^2\ $ с помощью критерия $\ \chi^2$-Пирсона.

Для генерации **нормально распределенных реализаций** случайных величин рекомендуется пользоваться встроенными в статистические пакеты функциями для генерации значений выборки из нормального распределения, которые задаются с помощью параметров математического ожидания $\mu$ и стандатрного отклонения $\sigma^2$.

3. **Сгенерировать выборку распределения Фишера на основе определения**. 

- На основе двух случайных реализаций $\ Y_1, Y_2\ $ случайных величин, распределенных по $\chi^2$-распределению со степенями свободы $\ d1, d2\ $ соответственно, сгенерировать выборку, распределенную по распределению Фишера $\ S \sim F(d1, d2)\ $ в соответствии с определением:

$$
S = \frac{Y_1 / d_1}{Y_2 / d_2}, \ S\sim F(d_1, d_2).
$$

- Для получившейся выборки построить гистограмму, визуализировать на гистограмме теоретическую плотность $\ F(d1, d2)\ $ распределения.

- Провести тест на распределение Фишера с помощью критерия $\ \chi^2$-Пирсона.

Для генерации выборки фиксированного размера из распределения $\chi^2$ рекомендуется пользоваться встроенными в статистические пакеты функциями для генерации случайных выборок из распределения $\chi^2$ с $df$ степенями свободы.

4. **Сгенерировать выборку t-распределения на основе определения**. 

- На основе $\ n \approx 2\div 8\ $ случайных реализаций $\ Y_1, Y_2, \dots, Y_n\ $ случайных величин, распределенных по стандартному нормальному распределению $\ Y_i \sim N(0, 1), \ i = 1, 2, \dots, n\ $, сгенерировать выборку $\ T \sim t(n)\ $, распределенную по $t$-распределению Стьюдента с $\ df = n\ $ степенями свободы в соответствии с определением:

$$
T = \frac{Y_0}{\sqrt{\frac{1}{n} \sum_{i=1}^{n} Y_i^2}}, \quad Y_0 \sim N(0, 1).
$$

- Реализовать вычисление аналитической плотности $t$-распределения Стьюдента с использованием бета-функции:

$$
{\displaystyle p_{t}(x\ |\ n)={\frac {1}{{\sqrt {n}}\,\mathrm {B} ({\frac {1}{2}},{\frac {n}{2}})}}\left(1+{\frac {x^{2}}{n}}\right)^{\!-{\frac {n+1}{2}}}},
$$
где

$$
{\displaystyle \mathrm {B} (x,y)=\int \limits _{0}^{1}t^{x-1}(1-t)^{y-1}\,dt,}
$$

определённая при ${\displaystyle \operatorname {Re} x>0}$, ${\displaystyle \operatorname {Re} y>0}$. 


- Для получившейся выборки построить гистограмму, визуализировать на гистограмме теоретическую плотность $\ t(n)\ $.

- Для получившейся выбрки провести тест на $t$-распределение Стьюдента с помощью критерия $\ \chi^2$-Пирсона, используя в качестве функции вероятности распределения $\ P_t(x\ |\ n)$:


$$
P_t(x\ |\ n) = \int_{-\infty}^{x} p_t(z\ |\ n) dz.
$$


5. Для всех заданий количество генерируемых значений выборки установить равным $N \approx 100 \div 1000$. Уровень надежности для критерия $\chi^2$-Пирсона или метода анаморфоз $\gamma = 0.95$.

# **Вопросы на защиту практической работы**

1. Центральная предельная теорема. Реализации случайно распределенных величин. Независимые величины. Степени свободы суммы независимо распределенных величин.

2. Определение нормального распределения. Спрямление для координат нормального распределения. Определение параметров нормального распределения через точечные оценки. Определение параметров нормального распределения, образованного суммой независимых величин, через ЦПТ.

3. Определение распределения Фишера. Аналитические формулы математического ожидания и дисперсии расределения Фишера.

4. t-распределение Стьюдента. Аппроксимации и определение функции плотности. Смесь нормально расределенных величин. Определение $Z$-оценок.