---
title: "Почти-периодические зависимости"
author: "Юрченков Иван Александрович, ассистент кафедры ПМ"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, dpi = 600, fig.align = "center", 
                      out.width = "70%", fig.width = 10, fig.height = 7)
```

## **Загрузка данных c Yahoo Finance**

```{r}
quantmod::getSymbols(Symbols = c("AAPL", "GOOG"), from = 0)
```

```{r}
library(dplyr)
ts <- data.frame(get("GOOG")) 
ts <- ts %>% 
  dplyr::mutate(Date = as.Date.character(x = rownames(ts), format = "%Y-%m-%d"),
                log_close = log(GOOG.Close),
                log_volume = log(GOOG.Volume))

data_frame_days_ts <- data.frame(Date = seq.Date(from = ts$Date[1], to = ts$Date[nrow(ts)], by = "days"))
df_ts <- dplyr::left_join(x = data_frame_days_ts, y = ts, by = "Date")
df_ts <- df_ts %>% tidyr::fill(names(df_ts), .direction = "down")


```



```{r}
pad_ts <- function(y_ts, x, pad = 1) {
  model <- lm(y_ts ~ x)
  coeffs <- model$coefficients
  
  diff_x <- x[2] - x[1]
  y_pad_model_left <- coeffs[2] * (x[1] - diff_x * (pad:1)) + coeffs[1]
  y_pad_model_right <- coeffs[2] * (x[length(x)] + diff_x * (1:pad)) + coeffs[1]
  return(
    c(y_pad_model_left, 
      y_ts, 
      y_pad_model_right)
  )
}


MariaRemark.out_of_trend <- function(ts, 
                                     delta, 
                                     mode = c("AP", "GP_log", "GP_lin", "HP")) {
    mode <- mode[1]
    lents <- length(ts)
    if (mode == "GP_log") {
        return(log((ts[1:(lents - 2*delta)] * ts[(2*delta + 1):lents]) / 
                      (ts[(delta + 1):(lents - delta)]^2)))
    } else if (mode == "GP_lin") {
        return((ts[1:(lents - 2*delta)] * ts[(2*delta + 1):lents]) - 
                  (ts[(delta + 1):(lents - delta)]^2))
    } else if (mode == "HP") {
        return(log((ts[1:(lents - 2*delta)]^2 + ts[(2*delta + 1):lents]^2) / 
                      ((ts[1:(lents - 2*delta)] + ts[(2*delta + 1):lents]) * 
                           ts[(delta + 1):(lents - delta)])))
    } else {
        return(log((ts[1:(lents - 2*delta)] + ts[(2*delta + 1):lents]) / 
                      (2 * ts[(delta + 1):(lents - delta)])))
    }
}


MariaRemark.Alter_Johns <- function(ts, p = 1) {
    lents <- length(ts)
    a <- numeric(length = lents)
    a[1] <- 0
    for (i in 1:(lents-1)) {
        a[i + 1] <- 1/(lents - i) * sum(abs(ts[1:(lents - i)] - ts[(1 + i):lents])^(p))^(1/p)
    }
    return(a)
}

```


```{r}
plot(pad_ts(ts$log_close, as.numeric(ts$Date), 1000), type = "o", pch = 19, cex = I(0.5), col = "blue")
grid()
```


```{r}
delta = 200
plot(x = df_ts$Date, 
     y = MariaRemark.out_of_trend(pad_ts(df_ts$GOOG.Close, as.numeric(df_ts$Date), delta), delta = delta, mode = "HP"), 
     type = "o", pch = 19, cex = I(0.5), lwd = I(0.5))
```



