---
title: "Практическая работа №6. Сглаживание временных рядов"
author: "Юрченков Иван Александрович, ассистент кафедры ПМ"
date: "`r Sys.Date()`"
mainfont: SourceSansPro
output:
  pdf_document:
    toc: no
    number_sections: no
    latex_engine: lualatex
    keep_tex: yes
    highlight: haddock
---


```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, dev="cairo_pdf")
```

Для выполнения практического задания необходимо:
    1. открыть папку, соответствующую своей группе;
    2. открыть папку с вариантом, совпадающим с вашим номером в списке.

В папке два файла, которые содержат разные временные ряды. В первом файле находится ряд с синусоидальным трендом. Во втором - с линейным.

Необходимо выделить тренд используя 4 метода:
    1. простое скользящее среднее (SMA);
    2. взвешенное скользящее среднее (WMA) особо типа;
    3. экспоненциальное сглаживание (EMA);
    4. двойное экспоненциальное сглаживание (DEMA).

Каждый метод требует подбора некоторых параметров:

1. SMA и WMA - размер окна, EMA - параметр сглаживания A, DEMA - параметр сглаживания вокруг тренда A и параметр сглаживания самого тренда B.

2. Необходимо подобрать оптимальные значения соотвествующих параметров, используя Q-статистику Льюнг-Бокса при m = 5. Оптимальными параметрами будем считать те, что минимизируют приведенную статистику.

3. В качестве размеров окна перебрать значения: 3, 5, 7, 9; в качестве параметров сглаживания: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9. Обратите внимание, что метод DEMA двухпараметрический, что требует выбрать оптимальную комбинацию сразу двух параметров.

4. После подбора оптимальных параметров провести тест Дарбина-Уотсона (m = 1, альфа = 0.95) на данных после исключения выделенного тренда для каждого метода и каждого ряда.

5. В отчете изобразить графики исходных данных, графики трендов при оптимальных параметрах у каждого метода для каждого ряда, расчетные формулы, а также результаты тестов Дарбина-Уотсона.



# **Темы вопросов на защиту практической работы**


1. Понятие временного ряда (ВР). Стационарность и нестационарность ВР. Примеры ВР. Аддитивная и мультипликативная модели ВР
2. Методы сглаживания ВР: MA, WMA, SMA, EMA. 
3. Лаговый оператор. Модели с распределенным лагом. Лаги Алмон.
4. Автокорреляционная и частная автокорреляционная функция. Модели AR. Процессы Маркова. Модели MA. Модели ARMA.
5. Информационные критерии качества модели (AIC, SIC). Моделирование нестационарных временных рядов. Модели ARIMA.