---
title: "Темы докладов"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Темы докладов
  
  1. ABC и XYZ анализ.
  
  2. VEN и FMR анализ.
  
  3. Дисперсионный анализ. (2 чел.)
  
  4. Визуализация данных: BarPlot, BoxPlot, ViolinPlot, RidgelinePlot, ScatterPlot. 
  
  5. Визуализация данных: ClevelandDotPlot, Histogram, ScatterPlot, Heatmap.
  
  6. Идентификация распределений. Критерии согласия. Критерий Колмогорова-Смирнова.
  
  7. Идентификация распределений. Графический метод. QQPlot.
  
  8. Проверка нормальности распределения. Критерий Шапиро-Уилка.
  
  9. Проверка нормальности распределения. Критерий асимметрии и эксцесса.
  
  10. Оценка параметров распределений. Метод максимизации правдоподобия.
  
  11. Приведение к нормальности. Преобразование Бокса-Кокса.
  
  12. Скользящие средние при прогнозировании временных рядов. Модели Брауна, Хольта и Хольта-Винтерса. (2 чел.)
  
  13. EM процесс определения параметров смеси известных распределений (2 чел.)
  
  14. Повторный отбор. Перестановочный тест. Исчерпывающий и бутстраповский перестановочные тесты (2 чел.)
  
  15. Проверки значимости на основе $t$-статистики. Множественное тестирование. Степени свободы.
  
  16. Проверка гипотез на основе статистики $\chi^2$. Подход на основе повторного отбора. Точная проверка Фишера. (2 чел.)
  
  17. Алгоритм многорукого бандита для множественной проверки статистических гипотез.
  
  18. Модельно-ориентированная кластеризация. Многомерное нормальное распределение. Смеси нормальных распределений. Выбор оптимального количества кластеров. (2 чел.)

  
  . 