% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
  \setmainfont[]{SourceSansPro}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Практическая работа №5. Линейная регрессия. Оценка адекватности модели, оценка доверительных интервалов параметров.},
  pdfauthor={Юрченков Иван Александрович, ассистент кафедры ПМ},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Практическая работа №5. Линейная регрессия. Оценка адекватности
модели, оценка доверительных интервалов параметров.}
\author{Юрченков Иван Александрович, ассистент кафедры ПМ}
\date{2022-10-17}

\begin{document}
\maketitle

\begin{verbatim}
## 
## Присоединяю пакет: 'dplyr'
\end{verbatim}

\begin{verbatim}
## Следующие объекты скрыты от 'package:stats':
## 
##     filter, lag
\end{verbatim}

\begin{verbatim}
## Следующие объекты скрыты от 'package:base':
## 
##     intersect, setdiff, setequal, union
\end{verbatim}

\begin{verbatim}
## Registered S3 method overwritten by 'GGally':
##   method from   
##   +.gg   ggplot2
\end{verbatim}

\hypertarget{ux43fux43eux441ux442ux430ux43dux43eux432ux43aux430-ux437ux430ux434ux430ux447ux438-ux434ux43bux44f-ux432ux44bux43fux43eux43bux43dux435ux43dux438ux44f-ux43fux440ux430ux43aux442ux438ux447ux435ux441ux43aux43eux439-ux440ux430ux431ux43eux442ux44b}{%
\section{\texorpdfstring{\textbf{Постановка задачи для выполнения
практической
работы}}{Постановка задачи для выполнения практической работы}}\label{ux43fux43eux441ux442ux430ux43dux43eux432ux43aux430-ux437ux430ux434ux430ux447ux438-ux434ux43bux44f-ux432ux44bux43fux43eux43bux43dux435ux43dux438ux44f-ux43fux440ux430ux43aux442ux438ux447ux435ux441ux43aux43eux439-ux440ux430ux431ux43eux442ux44b}}

Для выполнения практического задания необходимо:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Открыть папку, соотвествующую своей группе.
\item
  Открыть папку с вариантом, совпадающим с вашим номером в списке.
\end{enumerate}

В папке 3 файла с данными.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  1-ый файл содержит 2 ряда данных. Первый стоблец \(\ x\ \) содержит
  факторную переменную, второй столбец \(\ y\ \) результирующую. Для
  первого файла необходимо:
\end{enumerate}

\begin{itemize}
\item
  Оценить коэффициент корреляции Пирсона \(\ r(x, y)\ \) между двумя
  переменными в первом и втором столбце.
\item
  По шкале Чеддока оценить хакактеристику корреляционной связи между
  величинами.
\item
  Проверить статистическую значимость коэффициента корреляции Пирсона с
  помощью \(t\)-статистики.
\item
  Построить доверительный интервал для \(\ r(x, y)\ \) с надежностью
  \(\ \gamma\ = \ 0.95\).
\item
  Построить линейную регрессию между столбцами, оценить значение
  коэффициентов линейной зависимости.
\item
  Оценить адекватность модели \emph{с использованием критерия Фишера}.
\item
  Оценить значимость полученных коэффициентов прямой.
\item
  Построить доверительные интервалы для полученных коэффициентов.
\item
  Оценить интервал прогноза для линейной модели на \$ft = 3\$ значения
  вперед.
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  2-ой файл содержит 4 ряда данных. Первый ряд (столбец) содержит
  количественную факторную переменную, следующие два - качественную
  факторную переменную, последний - результирующую переменную. Для
  второго файла данных необходимо:
\end{enumerate}

\begin{itemize}
\item
  Необходимо с помощью теста Чоу обосновать необходимость деления
  выборки по одной из качественных факторных переменных.
\item
  Произвести разбиение и построить две линейных регрессии, оценить
  коэффициенты моделей.
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  3-ий файл содержит 2 ряда данных. Для третьего файла данных
  необходимо:
\end{enumerate}

\begin{itemize}
\item
  Необходимо двумя способами (тест Спирмена и тест Гольдфельда-Квандта)
  определить, присутствует ли в данных гетероскедастичность.
\item
  Построить линейную регрессию, оценить значения коэффициентов модели.
\item
  Оценить значимость полученных коэффициентов и адекватность модели.
\item
  Все расчеты проводить для уровня значимости \(\alpha = 0.05\).
\end{itemize}

\hypertarget{ux43fux440ux438ux43cux435ux440-ux43fux440ux43eux432ux435ux434ux435ux43dux438ux44f-ux440ux435ux433ux440ux435ux441ux441ux438ux43eux43dux43dux43eux433ux43e-ux430ux43dux430ux43bux438ux437ux430-ux434ux43bux44f-ux440ux44fux434ux430-ux434ux430ux43dux43dux44bux445}{%
\section{\texorpdfstring{\textbf{Пример проведения регрессионного
анализа для ряда
данных}}{Пример проведения регрессионного анализа для ряда данных}}\label{ux43fux440ux438ux43cux435ux440-ux43fux440ux43eux432ux435ux434ux435ux43dux438ux44f-ux440ux435ux433ux440ux435ux441ux441ux438ux43eux43dux43dux43eux433ux43e-ux430ux43dux430ux43bux438ux437ux430-ux434ux43bux44f-ux440ux44fux434ux430-ux434ux430ux43dux43dux44bux445}}

\hypertarget{ux438ux441ux441ux43bux435ux434ux443ux435ux43cux44bux439-ux440ux44fux434-ux434ux430ux43dux43dux44bux445}{%
\subsection{\texorpdfstring{\textbf{Исследуемый ряд
данных}}{Исследуемый ряд данных}}\label{ux438ux441ux441ux43bux435ux434ux443ux435ux43cux44bux439-ux440ux44fux434-ux434ux430ux43dux43dux44bux445}}

Для демонстрации проведения регрессионного анализа над рядом данных
выбран набор данных цен на алмазы (diamonds), являющийся классическим
набором данных для проверки регрессионных моделей и алгоритмов
идентификации, очистки или корректировки выбросов. Всего в наборе данных
10 переменных. В рассмотрение возьмем только две из них:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  carat \(-\) караты алмазов,
\item
  price \(-\) цена алмазов.
\end{enumerate}

Предварительный анализ данных рядов показывает их нелинейную
зависимость, похожую на параболическую, и чтобы избежать её в линейном
регрессионном анализе, принято решение \textbf{прологарифмировать} оба
ряда данных для спрямления зависимости в декартовых координатах.

Рассмотрим таблицу переменных парных данных
\(\left(ln(x), ln(y)\right)\) одинаковой длины без пропущенных значений
для данных о цене алмазов (\(y\)) с категориальными параметрами:
\(cut = Ideal\) (огранка), \(color = J\) (цвет), \(clarity = SI2\)
(чистота).

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 22\tabcolsep) * \real{0.0714}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 22\tabcolsep) * \real{0.1143}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 22\tabcolsep) * \real{0.0857}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 22\tabcolsep) * \real{0.0571}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 22\tabcolsep) * \real{0.1000}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 22\tabcolsep) * \real{0.0857}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 22\tabcolsep) * \real{0.0571}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 22\tabcolsep) * \real{0.1000}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 22\tabcolsep) * \real{0.0857}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 22\tabcolsep) * \real{0.0571}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 22\tabcolsep) * \real{0.1000}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 22\tabcolsep) * \real{0.0857}}@{}}
\caption{Таблица данных}\tabularnewline
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{n}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
ln(x)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
ln(y)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
ln(x)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
ln(y)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
ln(x)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
ln(y)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
ln(x)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
ln(y)
\end{minipage} \\
\midrule()
\endfirsthead
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
\textbf{n}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
ln(x)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
ln(y)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
ln(x)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
ln(y)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
ln(x)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
ln(y)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
n
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
ln(x)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
ln(y)
\end{minipage} \\
\midrule()
\endhead
\textbf{1} & -1.171 & 5.841 & \textbf{31} & 0.095 & 8.439 & \textbf{61}
& 0.571 & 8.958 & \textbf{91} & -1.109 & 5.903 \\
\textbf{2} & 0.020 & 7.965 & \textbf{32} & 0.231 & 8.446 & \textbf{62} &
0.531 & 9.048 & \textbf{92} & -0.892 & 6.594 \\
\textbf{3} & 0.000 & 8.150 & \textbf{33} & 0.182 & 8.447 & \textbf{63} &
0.698 & 9.307 & \textbf{93} & -0.942 & 6.111 \\
\textbf{4} & 0.000 & 8.168 & \textbf{34} & 0.215 & 8.448 & \textbf{64} &
0.723 & 9.327 & \textbf{94} & -0.635 & 6.752 \\
\textbf{5} & 0.077 & 8.171 & \textbf{35} & 0.199 & 8.450 & \textbf{65} &
0.703 & 9.334 & \textbf{95} & -0.673 & 6.786 \\
\textbf{6} & 0.049 & 8.193 & \textbf{36} & 0.239 & 8.454 & \textbf{66} &
0.723 & 9.336 & \textbf{96} & -0.654 & 6.829 \\
\textbf{7} & 0.010 & 8.225 & \textbf{37} & 0.231 & 8.464 & \textbf{67} &
0.708 & 9.389 & \textbf{97} & -0.616 & 6.886 \\
\textbf{8} & 0.039 & 8.223 & \textbf{38} & 0.182 & 8.465 & \textbf{68} &
0.732 & 9.407 & \textbf{98} & -0.635 & 6.910 \\
\textbf{9} & 0.010 & 8.243 & \textbf{39} & 0.182 & 8.465 & \textbf{69} &
0.698 & 9.439 & \textbf{99} & -0.462 & 6.971 \\
\textbf{10} & 0.058 & 8.227 & \textbf{40} & 0.239 & 8.472 & \textbf{70}
& 0.718 & 9.446 & \textbf{100} & -0.357 & 7.477 \\
\textbf{11} & 0.010 & 8.290 & \textbf{41} & 0.215 & 8.473 & \textbf{71}
& 0.708 & 9.451 & \textbf{101} & -0.357 & 7.510 \\
\textbf{12} & 0.010 & 8.293 & \textbf{42} & 0.231 & 8.489 & \textbf{72}
& 0.703 & 9.452 & \textbf{102} & -0.357 & 7.513 \\
\textbf{13} & 0.030 & 8.296 & \textbf{43} & 0.239 & 8.503 & \textbf{73}
& 0.728 & 9.455 & \textbf{103} & -0.274 & 7.514 \\
\textbf{14} & 0.030 & 8.307 & \textbf{44} & 0.239 & 8.521 & \textbf{74}
& 0.698 & 9.458 & \textbf{104} & -0.342 & 7.550 \\
\textbf{15} & 0.104 & 8.312 & \textbf{45} & 0.086 & 8.524 & \textbf{75}
& 0.829 & 9.488 & \textbf{105} & -0.329 & 7.563 \\
\textbf{16} & 0.104 & 8.317 & \textbf{46} & 0.207 & 8.534 & \textbf{76}
& 0.698 & 9.492 & \textbf{106} & -0.288 & 7.573 \\
\textbf{17} & 0.010 & 8.318 & \textbf{47} & 0.207 & 8.548 & \textbf{77}
& 0.798 & 9.525 & \textbf{107} & -0.357 & 7.624 \\
\textbf{18} & 0.104 & 8.319 & \textbf{48} & 0.293 & 8.570 & \textbf{78}
& 0.829 & 9.527 & \textbf{108} & -0.211 & 7.650 \\
\textbf{19} & 0.049 & 8.325 & \textbf{49} & 0.293 & 8.586 & \textbf{79}
& 0.829 & 9.582 & \textbf{109} & 0.020 & 7.867 \\
\textbf{20} & 0.095 & 8.333 & \textbf{50} & 0.322 & 8.660 & \textbf{80}
& 0.916 & 9.582 & \textbf{110} & 0.000 & 7.885 \\
\textbf{21} & 0.010 & 8.337 & \textbf{51} & 0.445 & 8.660 & \textbf{81}
& 0.916 & 9.632 & & & \\
\textbf{22} & 0.131 & 8.346 & \textbf{52} & 0.322 & 8.694 & \textbf{82}
& 0.904 & 9.644 & & & \\
\textbf{23} & 0.095 & 8.349 & \textbf{53} & 0.419 & 8.714 & \textbf{83}
& 0.916 & 9.680 & & & \\
\textbf{24} & 0.113 & 8.372 & \textbf{54} & 0.315 & 8.715 & \textbf{84}
& 0.928 & 9.680 & & & \\
\textbf{25} & 0.030 & 8.377 & \textbf{55} & 0.507 & 8.760 & \textbf{85}
& 1.102 & 9.683 & & & \\
\textbf{26} & 0.049 & 8.381 & \textbf{56} & 0.438 & 8.825 & \textbf{86}
& 0.900 & 9.709 & & & \\
\textbf{27} & 0.122 & 8.383 & \textbf{57} & 0.438 & 8.849 & \textbf{87}
& 0.967 & 9.736 & & & \\
\textbf{28} & 0.174 & 8.414 & \textbf{58} & 0.464 & 8.876 & \textbf{88}
& 0.959 & 9.753 & & & \\
\textbf{29} & 0.182 & 8.414 & \textbf{59} & 0.531 & 8.918 & \textbf{89}
& 1.001 & 9.787 & & & \\
\textbf{30} & 0.182 & 8.416 & \textbf{60} & 0.536 & 8.948 & \textbf{90}
& 0.956 & 9.818 & & & \\
\bottomrule()
\end{longtable}

Далее наши логарифмированные данные обозначим как
\(x := ln(x), \quad y := ln(y),\) и примем данные переменные как
рассматриваемые в нашем регрессионном анализе факторные и результирующие
соответственно.

В рассматриваемой таблице данных присутствует \(n = 110\) наблюдений для
каждой из рассматриваемых переменных.

Построим гистограммы распределений наших данных в каждой из переменных.

Таблица гистограммы для переменной \textbf{carat} выглядит следующим
образом:

\(\ \)

\begin{verbatim}
##        groupnames abs_freq   rel_freq    low   high     med     h
## 1  (-1.17,-0.846]        4 0.03636364 -1.170 -0.846 -1.0080 0.324
## 2 (-0.846,-0.522]        5 0.04545455 -0.846 -0.522 -0.6840 0.324
## 3 (-0.522,-0.197]       10 0.09090909 -0.522 -0.197 -0.3595 0.325
## 4  (-0.197,0.128]       29 0.26363636 -0.197  0.128 -0.0345 0.325
## 5   (0.128,0.453]       28 0.25454545  0.128  0.453  0.2905 0.325
## 6   (0.453,0.777]       19 0.17272727  0.453  0.777  0.6150 0.324
## 7     (0.777,1.1]       15 0.13636364  0.777  1.100  0.9385 0.323
\end{verbatim}

\(\ \)

Таблица гисограммы строится для дискретной оценки непрерывного закона
распределения и подсчета описательных статистик. В ней определяются из
выборки следующие столбцы:

\begin{itemize}
\item
  \textbf{groupnames} \(-\) названия групп непрерывных данных, метки
  интервалов групп для текстового обозначения их границ нижней и верхней
  соответственно,
\item
  \textbf{low} \(-\) значения нижней границы интервала данной группы,
\item
  \textbf{med} \(-\) середина интервала группы значений,
\item
  \textbf{high} \(-\) значения верхней границы интервала данной группы,
\item
  \textbf{abs\_freq} \(-\) значения абсолютных частот для группы
  значений выборки, количество значений в данной группе,
\item
  \textbf{rel\_freq} \(-\) значения относительных частот для группы
  значений выборки.
\end{itemize}

График гистограммы, построенной по таблице, для переменной
\textbf{carat} представлен далее.

\(\ \)

\begin{center}\includegraphics[width=0.6\linewidth]{Prac5_files/figure-latex/unnamed-chunk-6-1} \end{center}

\(\ \)

Таблица гистограммы, построенная для результирующей переменной
\textbf{price} для алмазов:

\(\ \)

\begin{verbatim}
##    groupnames abs_freq   rel_freq  low high   med    h
## 1 (5.84,6.41]        3 0.02727273 5.84 6.41 6.125 0.57
## 2 (6.41,6.98]        7 0.06363636 6.41 6.98 6.695 0.57
## 3 (6.98,7.55]        4 0.03636364 6.98 7.55 7.265 0.57
## 4 (7.55,8.11]        8 0.07272727 7.55 8.11 7.830 0.56
## 5 (8.11,8.68]       49 0.44545455 8.11 8.68 8.395 0.57
## 6 (8.68,9.25]       11 0.10000000 8.68 9.25 8.965 0.57
## 7 (9.25,9.82]       28 0.25454545 9.25 9.82 9.535 0.57
\end{verbatim}

\(\ \)

Также предложен график данной гистограммы для понимания присутствия в
ней возможного теоретического распределения:

\(\ \)

\begin{center}\includegraphics[width=0.6\linewidth]{Prac5_files/figure-latex/unnamed-chunk-8-1} \end{center}

\(\ \)

Для полученных выборок
\(\ X = (x_1, x_2, \dots, x_n), \quad Y = (y_1, y_2, \dots, y_n)\ \)
наши описательные статистики рассчитываем следующим образом:

\begin{itemize}
\tightlist
\item
  Среднее выборочное:
\end{itemize}

\[
\overline{x} = \frac{1}{n} \sum \limits_{i=1}^{n} x_i \approx 0.219, \quad \overline{y} = \frac{1}{n} \sum \limits_{i=1}^{n} y_i \approx 8.481
\]

\begin{itemize}
\tightlist
\item
  Средний квадрат отклонения для гистограммы с \(\ g\ \) групп:
\end{itemize}

Для каждой из групп \(\ i = \overline{1, g}\ \) подсчитаем границы
\(Z_i\) и \(L_i\):

\[
g = 1 + \lfloor log_2(n)\rfloor, \quad  h_x = \frac{max(X) - min(X)}{g}, \quad h_y = \frac{max(Y) - min(Y)}{g},
\]

\[
Z_j = min(X) + j \cdot h_x,\quad L_j = min(Y) + j \cdot h_y, \quad  j=0, 1, \dots, g.
\]

Рассчитаем середины групп \(\zeta_i\) для первой и \(\theta_i\) для
второй:

\[
\zeta_i = Z_{i} - Z_{i-1},\quad \theta_i = L_i - L{i-1}, \quad i=1,2,\dots, g.
\]

Далее подсчитаем средний квадрат отклонения по определению дисперсии:

\[
\sigma_x = \sqrt{\sum\limits_{i = 1}^{g} (\zeta_i - \overline{x})^2 \cdot p^x_i} \approx 0.488, \quad 
\sigma_y = \sqrt{\sum\limits_{i = 1}^{g} (\theta_i - \overline{x})^2 \cdot p^y_i} \approx 0.865.
\]

Парный график для зависимости с отображением ядерных оценок плотности
вероятности для обеих переменных:

\(\ \)

\begin{center}\includegraphics[width=0.85\linewidth]{Prac5_files/figure-latex/unnamed-chunk-10-1} \end{center}

\(\ \)

\hypertarget{ux43aux43eux440ux440ux435ux43bux44fux446ux438ux43eux43dux43dux44bux439-ux430ux43dux430ux43bux438ux437-ux447ux438ux441ux43bux43eux432ux44bux445-ux434ux430ux43dux43dux44bux445}{%
\subsection{\texorpdfstring{\textbf{Корреляционный анализ числовых
данных}}{Корреляционный анализ числовых данных}}\label{ux43aux43eux440ux440ux435ux43bux44fux446ux438ux43eux43dux43dux44bux439-ux430ux43dux430ux43bux438ux437-ux447ux438ux441ux43bux43eux432ux44bux445-ux434ux430ux43dux43dux44bux445}}

Корреляционный анализ данных позволяет ответить на вопрос о
функциональной связи между двумя переменными.

Коэффициент линейной корреляции Пирсона позволяет утверждать о линейной
связи между фактами (записями) переменных на основе численной оценки
данной связи. Численная оценка связи между переменными определяется
следующим образом:

\[
r(x,  y) = \frac{\overline{xy} - \overline{x} \cdot \overline{y}}{\sigma_x \sigma_y}, \quad \overline{xy} = \frac{1}{n} \sum \limits_{i=1}^{n} x_i \cdot y_i.
\]

Свойства коэффициента линейной корреляции:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \(r(x, y) \in [-1, 1].\)
\item
  Если \(r(x, y) > 0\), то связь положительная, если \(r(x,y) < 0\), то
  отрицательная, если \(r(x,y) = 0\), то линейной связи нет.
\item
  Если \(|r(x,y)| = 1\), то связь является линейной функциональной, то
  есть:
\end{enumerate}

\[y = kx + b.\]

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Чем ближе \(|r(x,y)|\) к \(1\), тем теснее связь между исследуемыми
  величинами.
\end{enumerate}

Рассчитаем связь между величинами по вычисленным описательным
статистикам по формуле выше для \(r(x, y)\). Полученное значение
корреляции \(r(x, y) \approx 0.973\), что говорит о сильной линейной
связи между переменными. По \textbf{шкале Чеддока} данная связь
характеризуется как \textbf{весьма высокая}.

Также оценим \textbf{значимость} коэффициента с помощью проверки по
следующему критерию. Рассчитаем \(t\)-статистику для данного ряда данных
и коэффициента линейной корреляции:

\[
t_r = |r| \cdot \sqrt{\frac{n - 2}{1 - r^2}}.
\]

Если полученное значение \(t\)-статистики выходит за границы интервала
\(\ |t_r| < t(n-2)_{1-\frac{\alpha}{2}}\ \), то принимается гипотеза
\textbf{H\_1}:

\begin{itemize}
\tightlist
\item
  \textbf{H\_1}: значение коэффициента линейной корреляции Пирсона
  значительно отличается от нуля.
\end{itemize}

Если данное значение не выходит за границы, то принимается
альтернативная гипотеза \textbf{H\_0}:

\begin{itemize}
\tightlist
\item
  \textbf{H\_0}: значение коэффициента линейной корреляции Пирсона
  незначительно отличается от нуля.
\end{itemize}

Вычислим значение \(t\)-статистики и получим, что
\(\ t_r \approx 43.479\ \), а значение границы интервала значимости для
\(t(n-2)\) распределения равно \(\ t(n-2)_{1- \frac{0.05}{2}} = 1.98\).

Из значений \(t_r\) видно, что уровень значимости преодолен, и значение
коэффициента линейной корреляции Пирсона значительно отличается от нуля
и его значение является статистически значимым.

\hypertarget{ux43fux43eux441ux442ux440ux43eux435ux43dux438ux435-ux43bux438ux43dux435ux439ux43dux43eux439-ux43cux43eux434ux435ux43bux438-ux440ux435ux433ux440ux435ux441ux441ux438ux438}{%
\subsection{\texorpdfstring{\textbf{Построение линейной модели
регрессии}}{Построение линейной модели регрессии}}\label{ux43fux43eux441ux442ux440ux43eux435ux43dux438ux435-ux43bux438ux43dux435ux439ux43dux43eux439-ux43cux43eux434ux435ux43bux438-ux440ux435ux433ux440ux435ux441ux441ux438ux438}}

Линейная модель регрессии \(-\) непрерывное описание линейной
зависимости наблюдаемой результирующей переменной от факторной
переменной:

\[
\hat{y}(x\ |\ a,b) = a\cdot x + b,
\] где \(\hat{y}(x) -\) линейная модель зависимости результирующей
переменной от факторной, \(\ a\ -\) параметр угла наклона прямолинейной
зависимости в декартовой плоскости, \(\ b\ -\) параметр пересечения
прямолинейной зависимости с осью \(\ x = 0\ \) при нулевом значении
факторной переменной.

Данные параметры модели рассчитываются исходя из решения задачи
минимизации квадрата ошибок модели на пространстве параметров от
имеющихся данных факторной и результирующей переменных на подвыборке :

\[
||\hat{y}(x\ |\ a,b) - y||_{L_2}^2 \to \underset{a, b}{min}.
\]

Чаще всего решается более простая задача минимизации квадрата ошибок
линейной модели по табличным данным:

\[
L(a, b) = \frac{1}{n} \sum \limits_{i=1}^{n}\left( a\cdot x_i + b - y_i  \right)^2 \to \underset{a,b}{min}.
\]

Данная поставленная задача может быть решена как \textbf{аналитически},
так и численно при помощи \textbf{метода градиентного спуска}.

При аналитическом решении выводятся формулы для подсчета коэффициентов
парной линейной регрессии и коэффициенты могут быть найдены из
соотношений:

\[
a = r(x, y) \cdot \frac{\sigma_y}{\sigma_x}, \quad b = \overline{y} - a\cdot \overline{x}.
\]

Рассчитав коэффициенты модели по формулам получим значения:

\begin{itemize}
\tightlist
\item
  угол наклона прямолинейной зависимости: \(a \approx 1.724\),
\item
  пересечение с осью \(x = 0\): \(b \approx 8.103\).
\end{itemize}

Отобразим график парной зависимости результирующей переменной от
объясняющей переменной и приведем итоговую модель зависимости:

\begin{center}\includegraphics[width=0.6\linewidth]{Prac5_files/figure-latex/unnamed-chunk-14-1} \end{center}

Данная зависимость имеет следующий вид:

\[
ln(price) = 1.724 \cdot ln(carat) + 8.103,
\]

или что в натуральном масштабе:

\[
price = 3304.701 \cdot carat^{1.724}
\]

\begin{center}\includegraphics[width=0.6\linewidth]{Prac5_files/figure-latex/unnamed-chunk-15-1} \end{center}

\hypertarget{ux442ux435ux441ux442-ux433ux435ux442ux435ux440ux43eux441ux43aux435ux434ux430ux441ux442ux438ux447ux43dux43eux441ux442ux438-ux434ux43bux44f-ux440ux44fux434ux430-ux434ux430ux43dux43dux44bux445}{%
\subsection{\texorpdfstring{\textbf{Тест гетероскедастичности для ряда
данных}}{Тест гетероскедастичности для ряда данных}}\label{ux442ux435ux441ux442-ux433ux435ux442ux435ux440ux43eux441ux43aux435ux434ux430ux441ux442ux438ux447ux43dux43eux441ux442ux438-ux434ux43bux44f-ux440ux44fux434ux430-ux434ux430ux43dux43dux44bux445}}

Гетероскедастичность \(-\) явление неоднородности дисперсии вдоль
линейной регрессионной зависимости. Данное явление сигнализирует о
наличии неоднородных остатков модели регрессии и значимого отличия СКО в
одном участке ошибок модели регрессии относительно данных от СКО другого
участка такой метрики.

Графически гетероскедстичность выглядит следующим образом:

\begin{center}\includegraphics[width=0.6\linewidth]{Prac5_files/figure-latex/unnamed-chunk-16-1} \end{center}

Хоть модель линейной регрессии и оценена через нулевое среднее ошибок,
но дисперсия вдоль выборки остатков модели неоднородна и зависит от
значения объясняющей переменной регрессии. В данном конкретном примере,
дисперсия остатков относительно модели регрессии изменяется также
линейно с ростом объясняющей переменной. Это один из возможных сценариев
гетероскедастичности.

Наличие гетероскедастичности случайных ошибок приводит к неэффективности
оценок, полученных с помощью метода наименьших квадратов. Кроме того, в
этом случае оказывается смещённой и несостоятельной классическая оценка
ковариационной матрицы МНК-оценок параметров. Следовательно,
статистические выводы о качестве полученных оценок могут быть
неадекватными.

Существует множество статистических тестов, позволяющих детектировать
гетероскедастичность зависимости:

\begin{itemize}
\tightlist
\item
  тест Голдфелда --- Куандта,
\item
  тест Бройша --- Пагана,
\item
  тест Парка,
\item
  тест Глейзера,
\item
  тест ранговой корреляции Спирмена,
\item
  и т.д.
\end{itemize}

В данной работе мы рассмотрим использование теста Голдфелда\(-\)Куандта
для идентификации гетероскедастичности на доле данных наблюдений.

\hypertarget{ux442ux435ux441ux442-ux433ux43eux43bux434ux444ux435ux43bux434ux430-ux43aux443ux430ux43dux434ux442ux430}{%
\subsubsection{\texorpdfstring{\textbf{Тест
Голдфелда\(-\)Куандта}}{Тест Голдфелда-Куандта}}\label{ux442ux435ux441ux442-ux433ux43eux43bux434ux444ux435ux43bux434ux430-ux43aux443ux430ux43dux434ux442ux430}}

Тест Голдфелда --- Квандта --- процедура тестирования
гетероскедастичности случайных ошибок регрессионной модели, для
предположения о пропорциональности случайных ошибок модели некоторой
переменной (также как случай выше, самый распространенный случай).

В первую очередь, данные упорядочиваются по убыванию независимой
переменной \(X\), относительно которой имеются подозрения на
гетероскедастичность.

Далее обычным МНК оценивается исходная регрессионная модель для двух
разных выборок --- первых \(\ m_1\ \) и последних \(\ m_2\ \) наблюдений
в данном упорядочении, где \(\ m_1 < n / 2, \quad m_2 < n/2\ \). Средние
\(\ n - (m_1 + m_2)\ \) наблюдений исключаются из рассмотрения. Чаще
всего объем исключаемых средних наблюдений --- порядка четверти общего
объема выборки. Тест работает и без исключения средних наблюдений, но в
этом случае мощность теста меньше.

Для полученных двух оценок регрессионной модели находят суммы квадратов
остатков и рассчитывают F-статистику, равную отношению большей суммы
квадратов остатков к меньшей

\[
{\displaystyle F={\frac {\sum \limits_{i=1}^{m_1} \left( \hat{y_1}(x_i) - y_i \right)^2 /(m_1-k)}{\sum \limits_{i=n-m_2 + 1}^{n} \left( \hat{y_2}(x_i) - y_i \right)^2/(m_2-k)}}},
\] где \(k\ -\) число факторных (объясняющих) переменных в линейной
зависимости, \(\hat{y_1}(x)\ -\) модель на первых \(m_1\) записях
отсортированных данных по объясняющей переменной, \(\hat{y_2}(x)\ -\)
модель на последних \(m_2\) записях отсортированных данных по
объясняющей переменной.

Данный тест имеет в основе статистику, распределенную по распределению
Фишера \(F(m_1-k, m_2-k)\) с \(\ d_1 = m_1 - k,\quad d_2 = m_2-k\ \)
степенями свободы. Если подсчитанная статистика по значению больше
критического значения распределения Фишера с заданными степенями свободы
и уровнем значимости \(F(m_1-k, m_2-k)_{1- \frac{\alpha}{2}}\), то
нулевая гипотеза отвергается и \textbf{гетероскедастичность имеет место}
для заданной линейной зависимости.

\hypertarget{ux442ux435ux441ux442-ux43dux430-ux433ux435ux442ux435ux440ux43eux441ux43aux435ux434ux430ux441ux442ux438ux447ux43dux43eux441ux442ux44c-ux434ux43bux44f-ux434ux430ux43dux43dux44bux445-ux446ux435ux43d-ux430ux43bux43cux430ux437ux43eux432-ux441-ux438ux441ux43fux43eux43bux44cux437ux43eux432ux430ux43dux438ux435ux43c-ux442ux435ux441ux442ux430-ux433ux43eux43bux434ux444ux435ux43bux434ux430-ux43aux443ux430ux43dux434ux442ux430}{%
\subsubsection{\texorpdfstring{\textbf{Тест на гетероскедастичность для
данных цен алмазов с использованием теста
Голдфелда\(-\)Куандта}}{Тест на гетероскедастичность для данных цен алмазов с использованием теста Голдфелда-Куандта}}\label{ux442ux435ux441ux442-ux43dux430-ux433ux435ux442ux435ux440ux43eux441ux43aux435ux434ux430ux441ux442ux438ux447ux43dux43eux441ux442ux44c-ux434ux43bux44f-ux434ux430ux43dux43dux44bux445-ux446ux435ux43d-ux430ux43bux43cux430ux437ux43eux432-ux441-ux438ux441ux43fux43eux43bux44cux437ux43eux432ux430ux43dux438ux435ux43c-ux442ux435ux441ux442ux430-ux433ux43eux43bux434ux444ux435ux43bux434ux430-ux43aux443ux430ux43dux434ux442ux430}}

Отсортируем выборку по переменной \(carat\) и возьмем по
\(m_1 = m_2 = \lfloor3n/8\lfloor\) записей с каждой стороны, что в сумме
составит \(\ m_1 + m_2 \approx \lfloor3n/4\rfloor\ \) записей. Тогда
можем рассчитать \(F\)-статистику:

Для \(\ n = 110\ \), \(\ m_1 = m_2 = 41\ \), \(\ k = 1\ \) ввиду того
что мы имеем дело с парной регрессией на одну объясняющую (факторную
переменную).

Модели на подвыборках оценены как:

\begin{itemize}
\item
  \(\hat{y_1}(x) = 2.03 \cdot x + 8.17\),
\item
  \(\hat{y_2}(x) = 1.719 \cdot x + 8.102\).
\end{itemize}

Тогда сумма квадратов ошибок для первой и второй модели соотвественно
равны \(\ RSS_1 \approx 0.669, \quad RSS_2 \approx 0.415\ \) и имеем
расчетную статистику:

\[
F = \frac{0.669 / 40}{0.415 / 40} = \frac{0.669}{0.415} \approx 1.6108.
\]

Получаем расчетную статистику \(F \approx 1.6108\), при критическом
значении \(F(40, 40)_{1 - \frac{0.05}{2}} \approx 1.875\). Рассчетная
статистика ненамного меньше критического значения распределения Фишера,
что всё же говорит о принятии нулевой гипотезы об отсутствии
гетероскедастичности в данной зависимости.

В полученной ситуации требуются повторные уточняющие тесты с различными
значениями \(m_1\) и \(m_2\) для достаточной достоверности теста.

\hypertarget{ux43eux446ux435ux43dux43aux430-ux430ux434ux435ux43aux432ux430ux442ux43dux43eux441ux442ux438-ux43eux446ux435ux43dux435ux43dux43dux43eux439-ux43cux43eux434ux435ux43bux438-ux440ux435ux433ux440ux435ux441ux441ux438ux438}{%
\subsection{\texorpdfstring{\textbf{Оценка адекватности оцененной модели
регрессии}}{Оценка адекватности оцененной модели регрессии}}\label{ux43eux446ux435ux43dux43aux430-ux430ux434ux435ux43aux432ux430ux442ux43dux43eux441ux442ux438-ux43eux446ux435ux43dux435ux43dux43dux43eux439-ux43cux43eux434ux435ux43bux438-ux440ux435ux433ux440ux435ux441ux441ux438ux438}}

Проверка значимости полученной модели называется проверкой адекватности.
Одним из способов проверки значимости линейной модели регрессии является
использование критерия Фишера, который заключается в расчёте
\(F(n-2, n-1)\)-распределенной статистике, определенной как:

\[
F = \frac{S^2_{\text{АД}}}{S^2_{\text{ОБЩ}}}, \quad S^2_{\text{АД}} = \frac{\sum\limits_{i=1}^{n} \left(  y_i - \hat{y}(x_i)\right)^2}{n-2}, \quad S^2_{\text{ОБЩ}} = \frac{\sum \limits_{i=1}^{n}\left(  y_i - \overline{y}\right)^2}{n - 1}.
\] Если полученное значение \(F\)-статистики равно или выше критического
значения \(F(n-2, n-1)_{1 - \frac{\alpha}{2}}\) при заданном уровне
значимости \(\alpha\), то модель признается неадекватной и принимается
гипотеза \(H_1\), в альтернативном случае принимается гипотеза \(H_0\) и
модель признается адекватной.

Рассмотрим рассчет статистики на примере данных о цене алмазов.

\hypertarget{ux440ux430ux441ux447ux435ux442-ux441ux442ux430ux442ux438ux441ux442ux438ux43aux438-ux434ux43bux44f-ux43eux446ux435ux43dux43aux438-ux430ux434ux435ux43aux432ux430ux442ux43dux43eux441ux442ux438-ux43cux43eux434ux435ux43bux438-ux440ux435ux433ux440ux435ux441ux441ux438ux438-ux446ux435ux43d-ux43dux430-ux430ux43bux43cux430ux437ux44b}{%
\subsubsection{\texorpdfstring{\textbf{Расчет статистики для оценки
адекватности модели регрессии цен на
алмазы}}{Расчет статистики для оценки адекватности модели регрессии цен на алмазы}}\label{ux440ux430ux441ux447ux435ux442-ux441ux442ux430ux442ux438ux441ux442ux438ux43aux438-ux434ux43bux44f-ux43eux446ux435ux43dux43aux438-ux430ux434ux435ux43aux432ux430ux442ux43dux43eux441ux442ux438-ux43cux43eux434ux435ux43bux438-ux440ux435ux433ux440ux435ux441ux441ux438ux438-ux446ux435ux43d-ux43dux430-ux430ux43bux43cux430ux437ux44b}}

Для полученной линейной модели зависимости натурального логарифма цены
алмазов от натурального логарифма карат произведем расчет полной суммы
квадратов (TSS) и суммы квадратов ошибок (RSS) как составных частей
\(F\)-статистики:

\[
RSS = \sum \limits_{i=1}^{n}(y_i - \hat{y}(x_i))^2 \approx 1.648, \quad TSS = \sum\limits_{i=1}^{n}(y_i - \overline{y})^2 \approx 82.185.
\]

Теперь произведем расчет \(F\)-статистики и получим:

\[
F = \frac{RSS / (n - 2)}{TSS / (n-1)} = \frac{1.648 \cdot 109}{82.185 \cdot 108} \approx 0.0202
\]

Критическое значение при уровне значимости \(\ \alpha = 0.05\ \) равно
\(\ F(108, 109)_{1 - \frac{0.05}{2}}\  = 1.459577\). Рассчетная
\(F\)-статистика значительно меньше критического значения распределения
Фишера, что говорит об адекватности полученной линейной модели
регрессии.

\hypertarget{ux43eux446ux435ux43dux43aux430-ux441ux442ux430ux442ux438ux441ux442ux438ux447ux435ux441ux43aux43eux439-ux437ux43dux430ux447ux438ux43cux43eux441ux442ux438-ux43aux43eux44dux444ux444ux438ux446ux438ux435ux43dux442ux43eux432-ux43bux438ux43dux435ux439ux43dux43eux439-ux43cux43eux434ux435ux43bux438-ux440ux435ux433ux440ux435ux441ux441ux438ux438}{%
\subsection{\texorpdfstring{\textbf{Оценка статистической значимости
коэффициентов линейной модели
регрессии}}{Оценка статистической значимости коэффициентов линейной модели регрессии}}\label{ux43eux446ux435ux43dux43aux430-ux441ux442ux430ux442ux438ux441ux442ux438ux447ux435ux441ux43aux43eux439-ux437ux43dux430ux447ux438ux43cux43eux441ux442ux438-ux43aux43eux44dux444ux444ux438ux446ux438ux435ux43dux442ux43eux432-ux43bux438ux43dux435ux439ux43dux43eux439-ux43cux43eux434ux435ux43bux438-ux440ux435ux433ux440ux435ux441ux441ux438ux438}}

\hypertarget{ux43eux446ux435ux43dux43aux430-ux43fux440ux43eux433ux43dux43eux437ux43dux43eux433ux43e-ux438ux43dux442ux435ux440ux432ux430ux43bux430-ux434ux43bux44f-ux43bux438ux43dux435ux439ux43dux43eux439-ux43cux43eux434ux435ux43bux438-ux440ux435ux433ux440ux435ux441ux441ux438ux438}{%
\subsection{\texorpdfstring{\textbf{Оценка прогнозного интервала для
линейной модели
регрессии}}{Оценка прогнозного интервала для линейной модели регрессии}}\label{ux43eux446ux435ux43dux43aux430-ux43fux440ux43eux433ux43dux43eux437ux43dux43eux433ux43e-ux438ux43dux442ux435ux440ux432ux430ux43bux430-ux434ux43bux44f-ux43bux438ux43dux435ux439ux43dux43eux439-ux43cux43eux434ux435ux43bux438-ux440ux435ux433ux440ux435ux441ux441ux438ux438}}

\hypertarget{ux442ux435ux43cux44b-ux432ux43eux43fux440ux43eux441ux43eux432-ux43dux430-ux437ux430ux449ux438ux442ux443-ux43fux440ux430ux43aux442ux438ux447ux435ux441ux43aux43eux439-ux440ux430ux431ux43eux442ux44b}{%
\section{\texorpdfstring{\textbf{Темы вопросов на защиту практической
работы}}{Темы вопросов на защиту практической работы}}\label{ux442ux435ux43cux44b-ux432ux43eux43fux440ux43eux441ux43eux432-ux43dux430-ux437ux430ux449ux438ux442ux443-ux43fux440ux430ux43aux442ux438ux447ux435ux441ux43aux43eux439-ux440ux430ux431ux43eux442ux44b}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Задачи корреляционного анализа. Выборочный коэффициент линейной
  корреляции (Пирсона) и его свойства. Шкала Чеддока.
\item
  Выборочный коэффициент линейной корреляции (Пирсона) и его свойства.
  Оценка значимости коэффициента корреляции.
\item
  Корреляция и причинная связь. Проблемы корреляционного анализа.
\item
  Ранговая корреляция. Коэффициент ранговой корреляции Спирмена.
\item
  Задачи регрессионного анализа. Функциональная и статистическая связь.
  Аппроксимационные модели. Параметрическое множество функций.
\item
  Линейная регрессия. Определение коэффициентов линейной модели методом
  наименьших квадратов.
\item
  Проверка значимости полученных коэффициентов модели. Проверка
  адекватности модели с помощью критерия Фишера.
\item
  Доверительный интервал прогноза. Проверка адекватности модели с
  помощью критерия Фишера.
\end{enumerate}

\end{document}
